spring.application.name=designer-company-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/designer_db
spring.datasource.username=postgres
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
file.upload-dir=uploads